export const PRODUCTS = {
  matHire: [
    {
      id: 'mat-standard',
      name: 'Standard Yoga Mat',
      description: 'Premium non-slip yoga mat, freshly sanitised',
      price: 250, // £2.50 in pence
      category: 'mat_hire' as const,
      emoji: '🧘',
    },
    {
      id: 'mat-premium',
      name: 'Premium Grip Mat',
      description: 'Extra thick premium mat with superior grip',
      price: 350,
      category: 'mat_hire' as const,
      emoji: '✨',
    },
  ],
  drinks: [
    {
      id: 'coffee-flat-white',
      name: 'Flat White',
      description: 'Double shot espresso with silky steamed milk',
      price: 350,
      category: 'drink' as const,
      subcategory: 'coffee',
      emoji: '☕',
      variants: [{ label: 'Milk', options: ['Whole', 'Oat', 'Almond', 'Soy'] }],
    },
    {
      id: 'coffee-latte',
      name: 'Latte',
      description: 'Smooth espresso with velvety steamed milk',
      price: 380,
      category: 'drink' as const,
      subcategory: 'coffee',
      emoji: '☕',
      variants: [{ label: 'Milk', options: ['Whole', 'Oat', 'Almond', 'Soy'] }],
    },
    {
      id: 'smoothie-green',
      name: 'Green Goddess',
      description: 'Spinach, banana, mango, coconut water & ginger',
      price: 650,
      category: 'drink' as const,
      subcategory: 'smoothie',
      emoji: '🥤',
    },
    {
      id: 'smoothie-berry',
      name: 'Berry Bliss',
      description: 'Mixed berries, banana, almond milk & honey',
      price: 650,
      category: 'drink' as const,
      subcategory: 'smoothie',
      emoji: '🫐',
    },
    {
      id: 'smoothie-mango',
      name: 'Mango Sunrise',
      description: 'Mango, pineapple, orange juice & turmeric',
      price: 650,
      category: 'drink' as const,
      subcategory: 'smoothie',
      emoji: '🥭',
    },
    {
      id: 'juice-cold-press',
      name: 'Cold Press Juice',
      description: 'Apple, carrot, ginger & lemon — pure energy',
      price: 550,
      category: 'drink' as const,
      subcategory: 'juice',
      emoji: '🍊',
      variants: [{ label: 'Flavour', options: ['Apple & Ginger', 'Carrot & Turmeric', 'Green Detox'] }],
    },
    {
      id: 'matcha-latte',
      name: 'Matcha Latte',
      description: 'Ceremonial grade matcha with steamed oat milk',
      price: 450,
      category: 'drink' as const,
      subcategory: 'coffee',
      emoji: '🍵',
      variants: [{ label: 'Milk', options: ['Oat', 'Almond', 'Whole', 'Soy'] }],
    },
  ],
  merchandise: [
    {
      id: 'pilates-socks',
      name: 'Grip Socks',
      description: 'Non-slip pilates socks with arch support',
      price: 1200,
      category: 'merchandise' as const,
      subcategory: 'accessories',
      emoji: '🧦',
      variants: [
        { label: 'Size', options: ['S/M', 'L/XL'] },
        { label: 'Colour', options: ['Sage', 'Clay', 'Black', 'Cream'] },
      ],
    },
    {
      id: 'hoodie',
      name: 'Studio Hoodie',
      description: 'Super soft organic cotton blend hoodie',
      price: 6500,
      category: 'merchandise' as const,
      subcategory: 'clothing',
      emoji: '👕',
      variants: [
        { label: 'Size', options: ['XS', 'S', 'M', 'L', 'XL'] },
        { label: 'Colour', options: ['Sage Green', 'Clay', 'Charcoal', 'Cream'] },
      ],
    },
    {
      id: 'leggings',
      name: 'Flow Leggings',
      description: 'High waist, four-way stretch yoga leggings',
      price: 5500,
      category: 'merchandise' as const,
      subcategory: 'clothing',
      emoji: '🩱',
      variants: [
        { label: 'Size', options: ['XS', 'S', 'M', 'L', 'XL'] },
        { label: 'Colour', options: ['Midnight', 'Sage', 'Clay', 'Blush'] },
      ],
    },
    {
      id: 'yoga-mat-purchase',
      name: 'Studio Yoga Mat',
      description: 'Our signature 6mm natural rubber yoga mat',
      price: 8500,
      category: 'merchandise' as const,
      subcategory: 'equipment',
      emoji: '🟩',
      variants: [{ label: 'Colour', options: ['Sage', 'Clay', 'Slate', 'Natural'] }],
    },
    {
      id: 'yoga-block',
      name: 'Cork Yoga Block',
      description: 'Sustainable cork blocks, sold as a pair',
      price: 2200,
      category: 'merchandise' as const,
      subcategory: 'equipment',
      emoji: '🟫',
    },
    {
      id: 'water-bottle',
      name: 'Studio Water Bottle',
      description: '500ml insulated stainless steel bottle',
      price: 3000,
      category: 'merchandise' as const,
      subcategory: 'accessories',
      emoji: '💧',
      variants: [{ label: 'Colour', options: ['Sage', 'Clay', 'Black', 'White'] }],
    },
  ],
  classes: [
    {
      id: 'single-class',
      name: 'Single Class',
      description: 'Drop-in to any class',
      price: 1800,
      category: 'class' as const,
      emoji: '🧘',
    },
    {
      id: 'class-pack-5',
      name: '5 Class Pack',
      description: '5 classes — save 10%',
      price: 8100,
      category: 'class_pack' as const,
      emoji: '📦',
    },
    {
      id: 'class-pack-10',
      name: '10 Class Pack',
      description: '10 classes — save 15%',
      price: 15300,
      category: 'class_pack' as const,
      emoji: '🎯',
    },
    {
      id: 'class-pack-20',
      name: '20 Class Pack',
      description: '20 classes — best value, save 20%',
      price: 28800,
      category: 'class_pack' as const,
      emoji: '⭐',
    },
    {
      id: 'membership-monthly',
      name: 'Unlimited Monthly',
      description: 'Unlimited classes every month',
      price: 9900,
      category: 'membership' as const,
      emoji: '♾️',
    },
    {
      id: 'membership-annual',
      name: 'Unlimited Annual',
      description: 'Best value — 2 months free',
      price: 99000,
      category: 'membership' as const,
      emoji: '🌟',
    },
  ],
}

export const formatPrice = (pence: number) =>
  new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP' }).format(pence / 100)
